export const OrderActionsTypes = {
  CREATE_ORDER_START: "CREATE_ORDER_START",
  CREATE_ORDER_SUCESS: "CREATE_ORDER_SUCESS",
  CREATE_ORDER_ERROR: "CREATE_ORDER_ERROR",

  SUBSCRIBE_ORDER_START: "SUBSCRIBE_ORDER_START",
  SUBSCRIBE_ORDER_SUCESS: "SUBSCRIBE_ORDER_SUCESS",
  SUBSCRIBE_ORDER_ERROR: "SUBSCRIBE_ORDER_ERROR",

  LIST_ORDER_START: "LIST_ORDER_START",
  LIST_ORDER_SUCESS: "LIST_ORDER_SUCESS",
  LIST_ORDER_ERROR: "LIST_ORDER_ERROR",

  CANCEL_ORDER_START: "CANCEL_ORDER_START",
  CANCEL_ORDER_SUCESS: "CANCEL_ORDER_SUCESS",
  CANCEL_ORDER_ERROR: "CANCEL_ORDER_ERROR",

  SET_EVALUATION_ORDER_START: "SET_EVALUATION_ORDER_START",
  SET_EVALUATION_ORDER_SUCESS: "SET_EVALUATION_ORDER_SUCESS",
  SET_EVALUATION_ORDER_ERROR: "SET_EVALUATION_ORDER_ERROR",

  START_ATTENDANCE_START: "START_ATTENDANCE_START",
  START_ATTENDANCE_SUCESS: "START_ATTENDANCE_SUCESS",
  START_ATTENDANCE_ERROR: "START_ATTENDANCE_ERROR",

  END_ATTENDANCE_START: "END_ATTENDANCE_START",
  END_ATTENDANCE_SUCESS: "END_ATTENDANCE_SUCESS",
  END_ATTENDANCE_ERROR: "END_ATTENDANCE_ERROR",

};


