export const AuthActionsTypes = {
  LOGIN_GOOGLE_START: 'LOGIN_GOOGLE_START',
  LOGIN_GOOGLE_SUCCESS: 'LOGIN_GOOGLE_SUCCESS',
  LOGIN_GOOGLE_ERROR: 'LOGIN_GOOGLE_ERROR',

  LOGOUT_GOOGLE_START: 'LOGOUT_GOOGLE_START',
  LOGOUT_GOOGLE_SUCCESS: 'LOGOUT_GOOGLE_SUCCESS',
  LOGOUT_GOOGLE_ERROR: 'LOGOUT_GOOGLE_ERROR',

  LOGIN_EMAIL_START: 'LOGIN_EMAIL_START',
  LOGIN_EMAIL_SUCESS: 'LOGIN_EMAIL_SUCESS',
  LOGIN_EMAIL_ERROR: 'LOGIN_EMAIL_ERROR',

  LOGOUT_EMAIL_START: 'LOGOUT_EMAIL_START',
  LOGOUT_EMAIL_SUCESS: 'LOGOUT_EMAIL_SUCESS',
  LOGOUT_EMAIL_ERROR: 'LOGOUT_EMAIL_ERROR',

  LOGIN_PHONE_START: 'LOGIN_PHONE_START',
  LOGIN_PHONE_SUCESS: 'LOGIN_PHONE_SUCESS',
  LOGIN_PHONE_ERROR: 'LOGIN_PHONE_ERROR',

  LOGOUT_PHONE_START: 'LOGOUT_PHONE_START',
  LOGOUT_PHONE_SUCESS: 'LOGOUT_PHONE_SUCESS',
  LOGOUT_PHONE_ERROR: 'LOGOUT_PHONE_ERROR',

  PROFILE_TYPE: 'PROFILE_TYPE',

  UPDATE_PROFILE_START: 'UPDATE_PROFILE_START',
  UPDATE_PROFILE_SUCESS: 'UPDATE_PROFILE_SUCESS',
  UPDATE_PROFILE_ERROR: 'UPDATE_PROFILE_ERROR',
};
