export const elderlyInfos = [
  {
    id: 1,
    name: "Maria Rita",
    task: "Trocar gás",
    distance: "3km",
    orderTime: "10min",
    photo: "/assets/images/oldman-1.jpg",
    action: "Ajudando",
    variant: "default",
    color: "#4e3681",
  },
  {
    id: 2,
    name: "Francisco",
    task: "EMERGÊNCIA",
    distance: "690 M",
    orderTime: "05min",
    photo: "/assets/images/oldman-8.jpg",
    action: "Socorrer Emergência",
    arrow: "/assets/svg/Vector.svg",
    variant: "emergency",
    colorTask: "#bc1610",
  },

  {
    id: 3,
    name: "Joaquina",
    task: "Trocar gás",
    distance: "3km",
    orderTime: "10min",
    photo: "/assets/images/oldman-4.jpg",
    action: "Oferecer ajuda",
    arrow: "/assets/svg/Vector.svg",
    variant: "gradient",
  },
  {
    id: 4,
    name: "José",
    task: "Jardinagem",
    distance: "690 m",
    orderTime: "05min",
    photo: "/assets/images/oldman-6.jpg",
    action: "Oferecer ajuda",
    arrow: "/assets/svg/Vector.svg",
    variant: "primaryVariant",
  },
  {
    id: 5,
    name: "Rosa Teresa",
    task: "EMERGÊNCIA",
    distance: "300 M",
    orderTime: "03min",
    photo: "/assets/images/oldman-3.jpg",
    action: "Socorrer Emergência",
    arrow: "/assets/svg/Vector.svg",
    variant: "emergency",
    colorTask: "#bc1610",
  },
];
